[package]
name = "spacetimedb-lib"
version.workspace = true
edition.workspace = true
license-file = "LICENSE"
description = "A common library for SpacetimeDB"
rust-version.workspace = true

[lib]
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[test]]
name = "serde"
required-features = ["serde"]

[features]
default = ["serde", "metrics_impls"]
serde = ["dep:serde", "spacetimedb-sats/serde"]
# Allows using `Arbitrary` impls defined in this crate.
proptest = ["dep:proptest", "dep:proptest-derive"]
# Allows using additional test methods.
test = ["proptest", "spacetimedb-sats/test"]
metrics_impls = ["dep:spacetimedb-metrics", "spacetimedb-sats/metrics_impls"]
enum-map = ["dep:enum-map"]

[dependencies]
spacetimedb-bindings-macro.workspace = true
spacetimedb-sats.workspace = true
spacetimedb-primitives.workspace = true
spacetimedb-metrics = { workspace = true, optional = true }
spacetimedb-data-structures.workspace = true

anyhow.workspace = true
bitflags.workspace = true
chrono.workspace = true
derive_more.workspace = true
enum-as-inner.workspace = true
hex.workspace = true
itertools.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true
blake3.workspace = true
enum-map = { workspace = true, optional = true }

#XXX: can't bring openssl or mio into this lib due to "publish" failing to compile them in wasm!
#eg. hyper,reqwest,native-tls,tokio all bring either of them.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
#tokio = { version= "1.44", default-features = false, features = ["rt", "sync", "time"] }
tokio.workspace = true #this "full" tokio causes 'mio' to fail to wasm compile see: https://github.com/tokio-rs/mio/pull/1856
#native-tls = "0.2"
native-tls.workspace=true
hyper.workspace=true
openssl.workspace=true
clap.workspace = true
reqwest.workspace=true
#This pki-types crate is actually an indirect(aka transitive) dep of reqwest above, but we want a feature enabled, so:
rustls-pki-types.workspace=true #needed here, to enable its 'trace_drop_and_zeroize' feature
#rustls-pki-types = { version = "1.11", features = ["trace_drop_and_zeroize"] }

# For the 'proptest' feature.
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

[dev-dependencies]
spacetimedb-sats = { path = "../sats", features = ["test"] }
bytes.workspace = true
serde_json.workspace = true
insta.workspace = true
ron.workspace = true

# Also as dev-dependencies for use in _this_ crate's tests.
proptest.workspace = true
proptest-derive.workspace = true

##no effect if here:
#[patch.crates-io]
##A version that has zeroize, because 1.12.0 or so, isn't yet released.
##Patched to have zeroize() method but doesn't zeroize on drop(this isn't enough for our uses!):
##rustls-pki-types = { git = "https://github.com/rustls/pki-types.git", rev = "b59e08d49911b10c423d25bd9040cfbe5a6042ff" }
#
##Patched to zeroize on drop(good for us):
#rustls-pki-types = { path = "/home/user/SOURCE/github/modified_forks/pki-types" }
##^ it's indirectly used though.
#
## a rustls that uses same pki-types patch.crates-io section from above and also enables pki-types' feature trace_drop_and_zeroize
##rustls = { path = "/home/user/SOURCE/github/rustls/rustls" }
##so rustls's Cargo.toml is modded to look like this:
### pki-types = { package = "rustls-pki-types", version = "1.11", features = ["alloc","trace_drop_and_zeroize"] }
###...
### ppatch.crates-io]
### rustls-pki-types = { path = "/home/user/SOURCE/github/modified_forks/pki-types" } #patched with ./zeroize_on_drop.patch
##XXX: this ^ (rustls hack) isn't needed if using the above inclusion of rustls-pki-types as dep here and .workspace=true in any Cargo.toml that has deps that use it.
#
##patched to not obscure connection errors behind ChannelClosed:
#hyper-util = { path ="/home/user/SOURCE/my/channelclosed.reqwest/hyper-util" }
#
##The current branch(TLS+mTLS) which added these changes to spacetimedb is also available as patch in: https://github.com/dare3path/spacetimedb-tls-patch
#

##no effect, if here or in root dir aka workspace Cargo.toml
#[patch.crates-io]
#rustls-pki-types = { path = "/home/user/SOURCE/github/modified_forks/pki-types" }
#hyper-util = { path ="/home/user/SOURCE/my/channelclosed.reqwest/hyper-util" }
